### ISSUE TITLE
Offhand bows and wands

### ISSUE THREAD

**Issue by Laike-Endaril** [Laike-Endaril/Faerun-Heroes#12]
You can glitch a bow or wand into the offhand slot using the vanilla "swap hands" keybind.

Once you have it in the offhand slot, it seems to use the attributes of the mainhand weapon, so if you put a mace in your mainhand, you can deal massive knockback with a bow

And then you can switch your mainhand to a high damage weapon and have a high damage bow

Etc.

**Comment by Laike-Endaril** [comment]
Possible solutions:
1. Prevent right-click from working for offhand
2. Prevent the item swap...but there might be another way of getting around that.  I suggest option 1

**Comment by Bluexin** [comment]
Should be fixed in https://github.com/Bluexin/BlueRPG/commit/2f290400e1933ad9216d1cc1e532d3eafcd39b9b, waiting for confirmation

**Comment by Laike-Endaril** [comment]
I'll poke LP about doing some of the server-side updates

**Comment by Laike-Endaril** [comment]
Fix confirmed on dev

**Comment by Laike-Endaril** [comment]
Have an issue server-side with the new version: https://pastebin.com/2X2H3NaY

**Comment by Laike-Endaril** [comment]
I must have missed when it happened, but this one seems to be fixed on live
