### ISSUE TITLE
Exp/level desync on dimension change

### ISSUE THREAD

**Issue by Laike-Endaril** [Laike-Endaril/Faerun-Heroes#2]
Changing dimensions sometimes desyncs your exp (will show level 1 on client, but is fine on server).

Relogging or gaining exp fixes the issue.

This happens with a random chance when switching dimensions, and was reproducible for me using a nether portal as well (not just the Instances portal).

Gear tooltips are effected (show level reqs in red), but are not actually disabled server-side (still give all bonuses, and weapons still deal damage).

Purely visual.

**Comment by Laike-Endaril** [comment]
This also has an effect on classes/skills

**Comment by Laike-Endaril** [comment]
During a test, artificially firing a PlayerChangedDimentionEvent (from the player's current dimention, to the same dimension) during a LivingHurtEvent caused the exp/level to sync again

**Comment by Laike-Endaril** [comment]
```
    @SubscribeEvent(priority = EventPriority.LOWEST)
    public static void playerChangeDim(PlayerEvent.PlayerChangedDimensionEvent event)
    {
        EntityPlayer player = event.player;
        if (player instanceof EntityPlayerMP && event.fromDim != event.toDim)
        {
            Thread thread = new Thread(() ->
            {
                System.out.println("Init");
                try
                {
                    Thread.sleep(3000);
                }
                catch (InterruptedException e)
                {
                    e.printStackTrace();
                }
                System.out.println("Fix");
                FMLCommonHandler.instance().getMinecraftServerInstance().addScheduledTask(() -> MinecraftForge.EVENT_BUS.post(new PlayerEvent.PlayerChangedDimensionEvent(player, player.dimension, player.dimension)));
            });
            thread.setName("FaerunUtils XP desync fix");
            thread.start();
        }
    }
```

A hacky fix is better than no fix, and this hacky fix is working.  I'll create a couple methods in my library's MCTools class for scheduling tasks this way (one for server, one for client), and make a build with the new lib and this fix soon

**Comment by Laike-Endaril** [comment]
@Bluexin Given, this is still a workaround, so if you want to fix it within BlueRPG itself later, might want to make a note for it in the tracker for BlueRPG (assuming you can reproduce while running only BlueRPG; may need to go back and forth to nether several times before it occurs).

**Comment by Bluexin** [comment]
This just means you're not firing the dim change event properly in the first place doesn't it?
I'm heavily against creating threads for this, those fuckers are extremely expensive. Might be ok for a couple players, but that's it.

**Comment by Laike-Endaril** [comment]
The exp/level desync happens with nether portals as well (not related to Instances)

But you're right, I should probably move that to a tick timer on the main thread.

**Comment by Bluexin** [comment]
I could never replicate it with the nether portal (aka it worked 100% with it for me).
Still seems like a hacky workaround.

**Comment by Laike-Endaril** [comment]
It is absolutely a hacky workaround :P

Not my fav either, but so far my attempts at a more immediate solution (with no delay) have failed.

Might be able to *request* a sync from the client after it finishes loading...if we can somehow detect such a thing...tell me if you have any ideas for that
